#!/usr/bin/env bash
# bash script that installs nginx web server
sudo apt remove --purge nginx -y
# Update the server
sudo apt update

# Install nginx
sudo apt-get install nginx -y

# Change ownership
sudo chown -R "$USER":"$USER" /var/www

# Update the default file displayed
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart nginx

# The 404 error message
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configuring Nginx server so that /redirect_me is redirected to another page
error404="error_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
replace="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

host=$(hostname)
str_head="\t\tadd_header X-Served-By $host;\n"

sudo sed -i "53i\\$error404\n\t$replace" /etc/nginx/sites-available/default
sudo sed -i -r "/^[^#].*try_files.*=404/ s|^|${str_head}|" /etc/nginx/sites-available/default

sudo systemctl restart nginx
sudo apt autoremove -y
