#!/usr/bin/env bash
# bash script that Install nginx web server

#update the server
sudo apt update
# installl nginx
sudo apt-get install nginx -y
# change ownership
sudo chown -R "$USER":"$USER" /var/www
# update the default file dispayed
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
# restart nginx
#the 404 error message
echo "Ceci n'est pas une page" >/var/www/html/404.html
# Configuring Nginx server so that /redirect_me is redirect to another page
error404="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
replace="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
host=$(hostname)
str_head="\t\tadd_header X-Served-By $host;\n"
sudo sed -i "53i\ $error404$replace" /etc/nginx/sites-available/default
sudo sed -i -r "/^[^#].*try_files.*=404/ s/^/${str_head}/" /etc/nginx/sites-available/default
sudo systemctl restart nginx
sudo apt autoremove -y
