#!/usr/bin/env bash
# a script that installs HAProxy server and configures it

#!/usr/bin/env bash
# a script that installs HAProxy server and configures it
# The script also ensures that the script can be managed through an init file

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

confg="\
frontend http
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 91190-web-01 100.25.34.49:80 check
	server 91190-web-02 54.90.6.47:80 check
"

sudo echo "$confg" >>/etc/haproxy/haproxy.cfg
sudo service haproxy restart
