#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd

f="/etc/passwd"
while IFS= read -r line; do
	i=1
	while [ $i -le 7 ]; do
		el=$(echo "$line" | cut -d ":" -f $i)
		col[$i]=$el
		i=$(( i + 1 ))
	done
	echo "The user ${col[1]} is part of the ${col[4]} gang, lives in ${col[6]} and rides ${col[7]}. ${col[3]}'s place is protected by the passcode ${col[2]}, more info about the user here: ${col[5]}"
done < "$f"
