#!/usr/bin/env bash
# script to print clock in 12 sys

hour=0

while ((hour <= 12)); do
	echo "Hour: $hour"

	minute=1
	while [ $minute -le 59 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
